apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: iotdemo
  namespace: logging
  annotations:
    kubernetes.io/ingress.class: "nginx"

spec:
  rules:
  - host: api.iot.ews.en.internal
    http:
      paths:
      - backend:
          serviceName: iotdemo
          servicePort: 80
        path: /
