apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-secret
  namespace: logging
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJoYXJib3Iud2lzZS1wYWFzLmlvIjogewoJCQkiYXV0aCI6ICJhbWx1TG5ocGJqcEJaSFpoYm5SbFkyaHFhVzU0YVc0eE1qTT0iCgkJfSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewoJCQkiYXV0aCI6ICJZV051WVdSMk9tcHBibDlrYjJOclpYST0iCgkJfQoJfSwKCSJIdHRwSGVhZGVycyI6IHsKCQkiVXNlci1BZ2VudCI6ICJEb2NrZXItQ2xpZW50LzE4LjA5LjcgKGxpbnV4KSIKCX0KfQ==
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotdemo
  namespace: logging
  labels:
    app: iotdemo
spec:
  replicas: 1
  selector:
    matchLabels:
        app: iotdemo
  template:
    metadata:
      labels:
        app: iotdemo
    spec:
      #imagePullSecrets:
      #- name: harbor-registry-secret
      containers:
        - name: iotdemo
          image: registry.cn-shanghai.aliyuncs.com/advantech-k8s/iotdemo:v1.0.0
          resources:
            requests:
              memory: "20Mi"
              cpu: "10m"
              ephemeral-storage: "100Mi"
            limits:
              memory: "100Mi"
              cpu: "165m"
              ephemeral-storage: "200Mi"
          imagePullPolicy: Always
          env:
          - name: sso_url
            value: http://api.sso.ews.en.internal/v4.0/
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  name: iotdemo
  namespace: logging
  labels:
    app: iotdemo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: iotdemo
