apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotdemo
  namespace: logging
  labels:
    app: iotdemo
spec:
  replicas: 1
  selector:
    matchLabels:
        app: iotdemo
  template:
    metadata:
      labels:
        app: iotdemo
    spec:
      containers:
        - name: iotdemo
          image: harbor.arfa.wise-paas.com/iotdemo/iotdemo:v1.0.0
          resources:
            requests:
              memory: "20Mi"
              cpu: "10m"
              ephemeral-storage: "100Mi"
            limits:
              memory: "100Mi"
              cpu: "165m"
              ephemeral-storage: "200Mi"
          imagePullPolicy: Always
          env:
          - name: sso_url
            value: http://api.sso.ews.en.internal/v4.0/
---
apiVersion: v1
kind: Service
metadata:
  name: iotdemo
  namespace: logging
  labels:
    app: iotdemo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: iotdemo
